if empty(glob('~/.vim/autoload/plug.vim'))
      silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
        autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin(expand('~/.vim/plugged'))
    Plug 'tpope/vim-commentary'
    Plug 'dylanaraps/wal.vim'
    Plug 'dylanaraps/fff.vim'
    Plug 'elixir-editors/vim-elixir'
    Plug 'ap/vim-css-color'
call plug#end()

colorscheme wal

nnoremap f :F<CR>
nnoremap <leader>d "_d
xnoremap <leader>d "_d
xnoremap <leader>p "_dP

set cmdheight=1
set incsearch
set smartcase
set showcmd
set showmode
set laststatus=2
set mouse=a
set et
set breakindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set backspace=indent,eol,start
set clipboard=unnamedplus
set background=dark
set number

