#!/bin/sh

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

pgrep -x feh > /dev/null || feh --bg-fill $wallpaper &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x xcompmgr > /dev/null || xcompmgr &
pgrep -x polybar > /dev/null || polybar -r topbar &

bspc monitor eDP1 -d 1 2 3 4 5 6

bspc config border_width 2
bspc config window_gap 2
bspc config normal_border_color		"$background"
bspc config active_border_color		"$background"
bspc config focused_border_color	"$color2"
bspc config presel_feedback_color	"$color1"
bspc config split_ratio         0.52
bspc config single_monocle      true
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a gnome-calculator state=floating
bspc rule -a Orage state=floating
