#!/bin/sh

# backgrounds directory
bgs_dir="$(pwd)/"

# terminal directory
st_dir="$HOME/Downloads/st-0.9/"

wal -s -i $bgs_dir$1

cd $st_dir
make clean
make
sudo make install

xrdb -load $HOME/.Xresources

bspc wm -r

betterlockscreen -u $bgs_dir$1
