#!/bin/sh

# backgrounds directory
bgs_dir="$HOME/Downloads/dotfiles/wallpapers/"

# terminal directory
st_dir="$HOME/Downloads/st-0.9/"

cd $bgs_dir
wal -s -i $bgs_dir$1 >/dev/null

cd $st_dir
make clean >/dev/null
make >/dev/null
printf 'needed root privileges for reinstall st\n'
sudo make install >/dev/null

xrdb -load $HOME/.Xresources >/dev/null

bspc wm -r

printf 'all done!\n'
